language: crystal
install:
  - shards install
  - shards build

script:
  - bin/ameba
  - crystal tool format --check
  - crystal spec --warnings all --error-on-warnings
  - crystal docs

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: docs
  on:
    branch: master
    condition: "$TRAVIS_EVENT_TYPE != cron"
