INHERIT: ./mkdocs-common.yml

site_name: Athena
site_url: https://athenaframework.org/
repo_url: https://github.com/athena-framework/athena

extra_css:
  - css/index.css
  - css/monorepo.css

plugins:
  - search
  - section-index
  - projects:
      projects_dir: src/components

watch:
  - ./mkdocs-common.yml

nav:
  - Introduction: README.md
  - Why Athena: why_athena.md
  - Getting Started:
      - getting_started/README.md
      - Routing & HTTP: getting_started/routing.md
      - Configuration: getting_started/configuration.md
      - Middleware: getting_started/middleware.md
      - Error Handling: getting_started/error_handling.md
      - Commands: getting_started/commands.md
      - Validation: getting_started/validation.md
      - Testing: getting_started/testing.md
  - Guides:
      - guides/README.md
      - Proxies & Load Balancers: guides/proxies.md
  - Bundle Reference:
      - bundle_reference.md
      - project://mercure-bundle
  - API Reference:
      - api_reference.md
      - project://clock
      - project://console
      - project://contracts
      - project://dependency_injection
      - project://dotenv
      - project://event_dispatcher
      - project://framework
      - project://http
      - project://http_kernel
      - project://image_size
      - project://mercure
      - project://mime
      - project://negotiation
      - project://routing
      - project://serializer
      - project://spec
      - project://validator

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/athena-framework
    - icon: fontawesome/brands/discord
      link: https://discord.gg/TmDVPb3dmr
