INHERIT: ../../../mkdocs-common.yml

site_name: NAMESPACE_NAME
site_url: https://athenaframework.org/NAMESPACE_NAME/
repo_url: https://github.com/athena-framework/COMPONENT_NAME

nav:
  - Introduction: README.md
  - Back to Manual: project://.
  - API:
    - Aliases: aliases.md
    - Top Level: top_level.md
    - '*'

plugins:
  - search
  - section-index
  - literate-nav
  - gen-files:
      scripts:
        - ../../../gen_doc_stubs.py
  - mkdocstrings:
      default_handler: crystal
      custom_templates: ../../../docs/templates
      handlers:
        crystal:
          crystal_docs_flags:
            - ../../../docs/index.cr
            - ./lib/athena-COMPONENT_NAME/src/athena-COMPONENT_NAME.cr
          source_locations:
            lib/athena-COMPONENT_NAME: https://github.com/athena-framework/COMPONENT_NAME/blob/v{shard_version}/{file}#L{line}
