INHERIT: ../../../mkdocs-common.yml

site_name: HTTPKernel
site_url: https://athenaframework.org/HTTPKernel/
repo_url: https://github.com/athena-framework/http-kernel

nav:
  - Introduction: README.md
  - Back to Manual: project://.
  - API:
      - Aliases: aliases.md
      - Top Level: top_level.md
      - '*'

plugins:
  - search
  - section-index
  - literate-nav
  - gen-files:
      scripts:
        - ../../../gen_doc_stubs.py
  - mkdocstrings:
      default_handler: crystal
      custom_templates: ../../../docs/templates
      handlers:
        crystal:
          crystal_docs_flags:
            - ../../../docs/index.cr
            - ./lib/athena-http_kernel/src/athena-http_kernel.cr
          source_locations:
            lib/athena-http_kernel: https://github.com/athena-framework/http-kernel/blob/v{shard_version}/{file}#L{line}
